# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f348c3f996d651b8afc671844463c9e677036cc6c45ad6d2a17e0a8bbe1479cc16cddc52e3864b24fa400816edf7684ee3ce843ce52009ff3e00ff9244498fa6

test:
  secret_key_base: 0c427af95f410a3bdcd87ee63fe80c372406517fe07f85d9b7dcec75f561978fca516d53ffafea07de52cb3b73719d8d1293fb580891f090bbefce0f341288b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
